<template>
  <div class="features-wrapper">
    <section class="container">
      <div class="columns is-centered">
        <div class="column">
          <lottie-player
            src="/animations/token.json"
            background="transparent"
            speed="1"
            style="width: 500px"
            loop
            autoplay
          ></lottie-player>
        </div>
        <div class="column">
          <div class="token-info">
            <h2 class="thirm-title text-left">THIRM Token</h2>
            <p>
              THIRM token is the multipurpose token used for paying fees,
              earning rewards, and participating in voting & governance. Since
              Thirm Protocol is DAO, all the earnings generated by protocol go
              to the token holders in the form of token buyback and burn.
            </p>
          </div>
          <div class="columns is-centered">
            <div class="column">
              <div class="token-info">
                <h2 class="thirm-title text-left">Tokenomics</h2>
                <ul class="tokenomic">
                  <li>UNISWAP LP</li>
                  <li>{{ pool }} THIRM</li>
                </ul>
                <ul class="tokenomic">
                  <li>Pending Expansion</li>
                  <li>{{ nextexpansion }} THIRM</li>
                </ul>
                <ul class="tokenomic">
                  <li>With Holders</li>
                  <li>{{ supply - pool }} THIRM</li>
                </ul>
              </div>
            </div>

            <div class="column">
              <div class="token-info">
                <h2 class="thirm-title text-left">TVL</h2>
                <ul class="tokenomic">
                  <li>NANO</li>
                  <li>{{ tNANO.supply }} NANO / {{ tNANO.tvl }} USD</li>
                </ul>
                <ul class="tokenomic">
                  <li>BTC</li>
                  <li>{{ tBTC.supply }} BTC / {{ tBTC.tvl }} USD</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script>
import axios from "axios";
async function requestTokendata() {
  return axios
    .get("https://api.thirm.com/token.json")
    .then(function(response) {
      return response.data;
    })
    .catch(function(error) {
      console.log(error);
      return null;
    });
}

async function requestTVLdata() {
  return axios
    .get("https://api.thirm.com/tvl.json")
    .then(function(response) {
      return response.data;
    })
    .catch(function(error) {
      console.log(error);
      return null;
    });
}
export default {
  data: function() {
    return {
      tBTC: {
        supply: "",
        tvl: "",
      },
      tNANO: {
        supply: "",
        tvl: "",
      },
      supply: 10,
      nextexpansion: 10,
      pool: 10,
      series: [0],
      chartOptions: {
        legend: { position: "bottom" },
        labels: ["Holders", "LP", "Rewards"],
        chart: {
          type: "donut",
        },
        responsive: [
          {
            breakpoint: 480,
            options: {
              chart: {
                width: 200,
              },
              legend: {
                position: "bottom",
              },
            },
          },
        ],
      },
    };
  },
  async mounted() {
    const tokenData = await requestTokendata();
    this.supply = parseFloat(tokenData["supply"]);
    this.pool = parseFloat(tokenData["pool"]);
    this.nextexpansion = parseFloat(tokenData["nextexpansion"]);
    this.series = [this.supply - this.pool, this.pool, this.nextexpansion];

    const tvlData = await requestTVLdata();
    this.tBTC.supply = parseFloat(tvlData.tBTC.supply).toFixed(8);
    this.tBTC.tvl = parseFloat(tvlData.tBTC.tvl).toFixed(8);

    this.tNANO.supply = parseFloat(tvlData.tNANO.supply).toFixed(8);
    this.tNANO.tvl = parseFloat(tvlData.tNANO.tvl).toFixed(8);
  },
};
</script>

<style scoped lang="scss">
.features-wrapper {
  padding: 60px 16px 60px 16px;
  margin: 60px 0 60px 0;
  background-image: radial-gradient(73% 147%, #eadfdf 59%, #ece2df 100%),
    radial-gradient(
      91% 146%,
      rgba(255, 255, 255, 0.5) 47%,
      rgba(0, 0, 0, 0.5) 100%
    );
  background-blend-mode: screen;
}
.zoom {
  transition: all 0.5s ease-in-out;
  .box {
    padding: 40px 0;
    color: #191919;
    font-size: 18px;
    font-weight: 500;
  }
  &:hover {
    transform: scale(1.2);
  }
}

.token-info {
  margin: 16px 0;
  .thirm-title {
    font-weight: 800;
    font-size: 32px;
    padding-bottom: 0;
  }
  p {
    padding: 16px 4px;
  }

  .tokenomic {
    padding: 16px 4px;
    li:first-child {
      color: #523ed6;
      font-weight: 500;
    }
  }
}
</style>
